const GET_USER_MYBOOKS = "user:GET_USER_MYBOOKS"
const GET_USER_FAVORITE = "user:GET_USER_FAVORITE"
const ADD_BOOK_TO_FAVORITE = "user:ADD_BOOK_TO_FAVORITE"
const DELETE_BOOK_FROM_FAVORITE = "user:DELETE_BOOK_FROM_FAVORITE"
const GET_USER_BY_ID = "user:GET_USER_BY_ID"
const GET_ALL_USER = "user:GET_ALL_USER"
const DELETE_USER = "user:DELETE_USER"
const UPGRADE_ROLE = "user:UPGRADE_ROLE"
const CREATE_ORDER = "order:CREATE_ORDER"
const GET_ALL_ORDER = "order:GET_ALL_ORDER"
const DELETE_ORDER = "order:DELETE_ORDER"
const UPDATE_ORDER = "order:UPDATE_ORDER"
const GET_ORDER_BY_ID = "order:GET_ORDER_BY_ID"
const GET_ALL_COUPON = "coupon:GET_ALL_COUPON"
const DELETE_COUPON = "coupon:DELETE_COUPON"
const GET_COUPON_BY_ID = "coupon:GET_COUPON_BY_ID"
const ADD_COUPON = "coupon:ADD_COUPON"
const UPDATE_COUPON = "coupon:UPDATE_COUPON"
const GET_ALL_CART = "cart:GET_ALL_CART"
const GET_MY_CART = "cart:GET_MY_CART"
const REMOVE_ITEMS = "cart:REMOVE_ITEMS"
const UPDATE_CART = "cart:UPDATE_CART"
const ADD_BOOK_IN_CART = "cart:ADD_BOOK_IN_CART"
const DELETE_BOOK_IN_CART = "cart:DELETE_BOOK_IN_CART"
const ADD_NEW_BOOK = "book:ADD_NEW_BOOK"
const DELETE_BOOK= "book:DELETE_BOOK"
const UPDATE_BOOK = "book:UPDATE_BOOK"
const GET_BOOK_BY_ID = "book:GET_BOOK_BY_ID"
const GET_ALL_BOOK = "book:GET_ALL_BOOK"



module.exports = {
    GET_USER_MYBOOKS,
    GET_USER_FAVORITE,
    ADD_BOOK_TO_FAVORITE,
    DELETE_BOOK_FROM_FAVORITE,
    GET_USER_BY_ID,
    GET_ALL_USER,
    DELETE_USER,
    UPGRADE_ROLE,
    CREATE_ORDER,
    GET_ALL_ORDER,
    DELETE_ORDER,
    UPDATE_ORDER,
    GET_ORDER_BY_ID,
    GET_ALL_COUPON,
    DELETE_COUPON,
    GET_COUPON_BY_ID,
    ADD_COUPON,
    UPDATE_COUPON,
    GET_ALL_CART,
    GET_MY_CART,
    REMOVE_ITEMS,
    UPDATE_CART,
    ADD_BOOK_IN_CART,
    DELETE_BOOK_IN_CART,
    ADD_NEW_BOOK,
    DELETE_BOOK,
    UPDATE_BOOK,
    GET_BOOK_BY_ID,
    GET_ALL_BOOK
}