const GET_USER_MYBOOKS = "user:GET_USER_MYBOOKS"
const GET_USER_FAVORITE = "user:GET_USER_FAVORITE"
const ADD_BOOK_TO_FAVORITE = "user:ADD_BOOK_TO_FAVORITE"
const DELETE_BOOK_FROM_FAVORITE = "user:DELETE_BOOK_FROM_FAVORITE"
const GET_USER = "user:GET_USER"
const GET_ALL_USERS = "user:GET_ALL_USERS"
const DELETE_USER = "user:DELETE_USER"
const UPGRADE_ROLE = "user:UPGRADE_ROLE"



const CREATE_ORDER = "order:CREATE_ORDER"
const GET_ALL_ORDERS = "order:GET_ALL_ORDERS"
const GET_MY_ORDERS = "order:GET_MY_ORDERS"
const GET_ORDER = "order:GET_ORDER"
const GET_ALL_ORDER_TO_SELLER = "order:GET_ALL_ORDER_TO_SELLER"
const GET_ALL_ORDER_TO_BOOK = "order:GET_ALL_ORDER_TO_BOOK"



const GET_ALL_COUPONS = "coupon:GET_ALL_COUPONS"
const DELETE_COUPON = "coupon:DELETE_COUPON"
const GET_COUPON = "coupon:GET_COUPON_BY_ID"
const ADD_COUPON = "coupon:ADD_COUPON"
const UPDATE_COUPON = "coupon:UPDATE_COUPON"
const GET_MY_COUPONS = "coupon:GET_MY_COUPONS"


const GET_ALL_CARTS = "cart:GET_ALL_CARTS"
const GET_MY_CART = "cart:GET_MY_CART"
const APPLY_COUPON = "cart:APPLY_COUPON"
const ADD_BOOK_IN_CART = "cart:ADD_BOOK_IN_CART"
const DELETE_BOOK_IN_CART = "cart:DELETE_BOOK_IN_CART"
const GET_CART = "cart:GET_CART"


const ADD_NEW_BOOK = "book:ADD_NEW_BOOK"
const DELETE_BOOK= "book:DELETE_BOOK"
const UPDATE_BOOK = "book:UPDATE_BOOK"
const GET_BOOK = "book:GET_BOOK"
const GET_ALL_BOOKS = "book:GET_ALL_BOOKS"



module.exports = {
    GET_USER_MYBOOKS,
    GET_USER_FAVORITE,
    ADD_BOOK_TO_FAVORITE,
    DELETE_BOOK_FROM_FAVORITE,
    GET_USER,
    GET_ALL_USERS,
    DELETE_USER,
    UPGRADE_ROLE,


    CREATE_ORDER,
    GET_ALL_ORDERS,
    GET_MY_ORDERS,
    GET_ALL_ORDER_TO_SELLER,
    GET_ALL_ORDER_TO_BOOK,
    GET_ORDER,


    GET_ALL_COUPONS,
    DELETE_COUPON,
    GET_COUPON,
    ADD_COUPON,
    UPDATE_COUPON,
    GET_MY_COUPONS,


    GET_ALL_CARTS,
    GET_MY_CART,
    GET_CART,
    APPLY_COUPON,
    ADD_BOOK_IN_CART,
    DELETE_BOOK_IN_CART,

    
    ADD_NEW_BOOK,
    DELETE_BOOK,
    UPDATE_BOOK,
    GET_BOOK,
    GET_ALL_BOOKS
}